'use client';
import Link from 'next/link';
import { useEffect } from 'react';
import { Week, resources, disclaimer } from '@/data/course';
import { useCourseProgress } from '@/lib/progress';
import { Checklist, PracticalTaskCard, ProgressBar, ResourceCard, VideoCard, VocabularyCard, WeekNavigation } from './course';
export function WeekDetail({week}:{week:Week}) {
 const {progress,ready,error,visit,note,percent}=useCourseProgress();
 useEffect(()=>{if(ready)visit(week.week);},[ready,week.week,visit]);
 const value=percent(week.week);
 return <><Link href="/course" className="text-link back-link">← 返回课程路线</Link><div className="page-top"><div><span className="eyebrow">MONTH {String(week.month).padStart(2,'0')} / WEEK {String(week.week).padStart(2,'0')}</span><h1>{week.titleZh} <span className="english-title">{week.titleEn}</span></h1><p>{week.description}</p></div><span className="quiet-badge">第 {week.week} / 24 周</span></div>{value===100&&<div className="success" role="status">{week.week===24?'✧ 毕业项目已完成！你的家庭营养指南，是把知识带回生活的第一步。':'✓ 本周已完成。记得把学到的一点知识，带到下一餐。'}</div>}<div className="lesson-layout"><div className="lesson-main"><section className="panel"><span className="eyebrow">THIS WEEK, YOU WILL LEARN</span><h2>本周学习目标</h2><p>完成本周后，你应该能够：</p><ul className="objectives">{week.objectives.map(o=><li key={o}>{o}</li>)}</ul></section><section className="panel"><h2>认识本周的营养概念</h2><p>带着这些关键词阅读资料，并尝试用自己的话解释。</p><div className="topics">{week.topics.map((t,i)=><div key={t.en}><span>{String(i+1).padStart(2,'0')}</span><div><strong>{t.zh}</strong><small>{t.en}</small></div></div>)}</div><blockquote>{week.reflection}</blockquote></section><section><div className="section-title"><div><h2>学习资源</h2><p>从可靠的来源开始，英文资料可配合浏览器翻译。</p></div></div><div className="resource-grid">{resources.filter(r=>week.resourceIds.includes(r.id)).map(r=><ResourceCard key={r.id} resource={r}/>)}</div></section><section className="panel"><h2>一起看一看</h2>{week.videos.map((v,i)=><VideoCard key={i} video={v}/>)}</section><PracticalTaskCard week={week}/>{week.week===17&&<section className="panel"><h2>饮食日记示例</h2><p>这是记录方式示例，并非个人饮食处方。请在下方笔记中记录自己的饮食。</p><div className="diary-example">{[['早餐','咖啡、全麦面包、鸡蛋'],['午餐','米饭、青菜、豆腐'],['晚餐','汤面、蔬菜、鱼'],['零食','一份水果'],['饮料','水、茶']].map(([meal,food])=><div key={meal}><strong>{meal}</strong><span>{food}</span><small>另记：份量、时间、烹调方法</small></div>)}</div></section>}<section className="panel"><div className="section-title"><h2>我的学习笔记</h2><span className="saved-state" role="status">{!ready?'正在读取…':error?'尚未保存':'已自动保存到此浏览器'}</span></div><label htmlFor="weekly-notes">记下你的发现、疑问，或本周实践的结果。</label><textarea id="weekly-notes" rows={8} disabled={!ready} placeholder="今天我学到…\n我想在下一餐试试…" value={progress.weeks[week.week]?.notes??''} onChange={e=>note(week.week,e.target.value)}/><small className="muted">笔记仅保存在当前浏览器，不会同步到其他设备。</small></section></div><aside className="lesson-aside"><section className="panel checklist-panel"><div className="progress-label"><h2>本周学习清单</h2><strong>{value}%</strong></div><ProgressBar value={value}/><p>完成所有必修项目，即完成本周。</p><Checklist week={week}/></section><section className="panel"><span className="eyebrow">A LITTLE ENGLISH</span><h2>每日10分钟 · 营养英语</h2><VocabularyCard week={week}/></section><p className="disclaimer">{disclaimer}</p></aside></div><WeekNavigation id={week.week}/></>;
}
