import type {
  Lesson,
  LessonBlock,
  Localized,
  KeyTerm,
  Question,
} from "../lesson-types";
const l = <T>(zh: T, en: T): Localized<T> => ({ zh, en });
const p = (text: string): LessonBlock => ({ type: "paragraph", text });
const list = (...items: string[]): LessonBlock => ({
  type: "bulletList",
  items,
});
const call = (
  variant: "important" | "example" | "warning" | "remember",
  title: string,
  text: string,
): LessonBlock => ({ type: "callout", variant, title, text });
const example = (title: string, body: string): LessonBlock => ({
  type: "example",
  title,
  body,
});
const comparison = (
  ...columns: { title: string; items: string[] }[]
): LessonBlock => ({ type: "comparison", columns });
const term = (
  id: string,
  zh: string,
  en: string,
  definitionZh: string,
  definitionEn: string,
  exampleZh?: string,
  exampleEn?: string,
): KeyTerm => ({
  id,
  term: l(zh, en),
  definition: l(definitionZh, definitionEn),
  ...(exampleZh && exampleEn ? { example: l(exampleZh, exampleEn) } : {}),
});
const question = (
  id: string,
  prompt: Localized,
  options: Localized[],
  answer: number,
  feedback: Localized,
): Question => ({
  id,
  prompt,
  options: options.map((text, i) => ({ id: String(i), text })),
  answerId: String(answer),
  feedback,
});
// Original teaching text, checked against the linked sources on 2026-09-25.
// Translations are authored here, never generated by a runtime translation service.
export const week01Lesson: Lesson = {
  status: "published",
  reviewedAt: "2026-09-25",
  sourceIds: ["who", "dri", "nutrition-terms", "energy"],
  introduction: l(
    "一碗饭、一颗蛋、一盘青菜：看起来很熟悉，但身体从中得到了什么？这一周，我们从餐桌走进营养学。你不需要先懂生物学，也不需要计算每天该吃多少卡路里。先学会辨认食物、营养素和能量，之后的课程就有了基础。",
    "A bowl of rice, an egg and a plate of vegetables are familiar foods. But what does your body get from them? This week starts at the family table. You do not need a science background or a daily calorie target. Learning to distinguish foods, nutrients and energy will give you a foundation for the weeks ahead.",
  ),
  objectives: l(
    [
      "解释食物、营养素和营养学的区别。",
      "认识碳水化合物、蛋白质、脂肪，以及维生素和矿物质的基本角色。",
      "理解卡路里衡量的是能量，而不是食物的整体质量。",
      "区分 RDA、EAR 和 UL，并知道 UL 不是目标。",
      "用一顿家常饭，练习识别食物中的多种营养成分。",
    ],
    [
      "Explain the difference between food, nutrients and nutrition.",
      "Recognise the broad roles of carbohydrate, protein, fat, vitamins and minerals.",
      "Understand that calories measure energy, not overall food quality.",
      "Distinguish RDA, EAR and UL, and explain why UL is not a target.",
      "Identify several nutrients in an ordinary family meal.",
    ],
  ),
  sections: [
    {
      id: "what-is-nutrition",
      title: l("1.1 什么是营养学？", "1.1 What is nutrition?"),
      termIds: ["nutrition", "nutrient"],
      sourceIds: ["nutrition-terms"],
      content: l(
        [
          p(
            "营养学研究食物中的成分，以及身体如何利用它们来维持生命、成长和保持健康。“我吃了什么”和“身体得到了什么”是两个相连但不同的问题。",
          ),
          p(
            "食物是我们买、煮和吃的东西，例如米饭、鸡蛋、豆腐和木瓜。营养素则是食物中身体需要利用的物质，例如蛋白质、脂肪、维生素和矿物质。营养素不是只有补充剂里才有，它们本来就存在于食物之中。",
          ),
          example(
            "把一顿早餐拆开来看",
            "你吃的是鸡蛋三明治。面包主要提供碳水化合物，也含少量蛋白质；鸡蛋提供蛋白质、脂肪和一些维生素、矿物质。胃肠道会把许多大分子分解成可吸收的小单位，身体再利用它们。食物的名字和营养素的名字不是同一回事。",
          ),
          p(
            "可以把食物想成装着不同材料的包裹：一个包裹里往往有不止一种材料。这个比喻帮助我们分类，但真实的消化和吸收更复杂；不是吃进去的每一部分都一定被身体吸收。",
          ),
          call(
            "remember",
            "先记住这个区别",
            "米饭是一种食物；碳水化合物是一类营养素。不要把“某食物含有某营养素”理解成“这食物只有这一种营养素”。",
          ),
        ],
        [
          p(
            "Nutrition is the study of substances in food and how the body uses them to stay alive, grow and support health. “What did I eat?” and “What did my body obtain?” are connected, but they are different questions.",
          ),
          p(
            "Foods are the things we buy, cook and eat: rice, eggs, tofu and papaya. Nutrients are substances in those foods that the body needs and uses, such as protein, fats, vitamins and minerals. Nutrients are not found only in supplements; they are already present in everyday food.",
          ),
          example(
            "Unpack a familiar breakfast",
            "You eat an egg sandwich. The bread provides mainly carbohydrate and some protein. The egg provides protein, fat and some vitamins and minerals. Digestion breaks many large molecules into smaller units that can be absorbed and used. The name of the food is not the name of a nutrient.",
          ),
          p(
            "Think of a food as a parcel containing several useful materials. One parcel usually contains more than one material. This analogy helps with classification, although real digestion and absorption are more complex: not everything swallowed is necessarily absorbed.",
          ),
          call(
            "remember",
            "Keep these ideas separate",
            "Rice is a food; carbohydrate is a class of nutrient. “This food contains a nutrient” does not mean “this food contains only that nutrient.”",
          ),
        ],
      ),
    },
    {
      id: "macronutrients",
      title: l(
        "1.2 宏量营养素：身体需要的大类",
        "1.2 Macronutrients: the bigger building blocks",
      ),
      termIds: ["macronutrient", "carbohydrate", "protein", "fat"],
      sourceIds: ["who", "nutrition-terms"],
      content: l(
        [
          p(
            "碳水化合物、蛋白质和脂肪是三类供能的宏量营养素。“宏量”描述的是需要量相对较大，通常以克计，不代表其中某一类比另一类更重要。水也需要大量摄入，但不提供能量；这里先讨论三类供能营养素。",
          ),
          comparison(
            {
              title: "碳水化合物",
              items: [
                "提供身体可以利用的能量。",
                "常见于米饭、面条、水果、豆类等。",
                "包括糖、淀粉和纤维；纤维不像淀粉那样被消化。",
              ],
            },
            {
              title: "蛋白质",
              items: [
                "提供氨基酸，用于构建与修复组织。",
                "酶等身体运作所需的物质也由蛋白质构成。",
                "鸡蛋、鱼、豆腐和豆类都是来源。",
              ],
            },
            {
              title: "脂肪",
              items: [
                "提供能量，并参与细胞结构。",
                "帮助吸收维生素 A、D、E、K。",
                "食用油、坚果、鱼和鸡蛋中都有脂肪。",
              ],
            },
          ),
          p(
            "同一种食物可以同时提供这几类成分。例如豆腐提供蛋白质，也含脂肪；米饭也不是纯碳水化合物。我们说某种食物“富含”某类营养素，只是在强调它较突出的特点。",
          ),
          call(
            "important",
            "三类都有合理的角色",
            "不要因为听见“碳水”或“脂肪”就自动排除整类食物。食物种类、份量和长期的整体搭配都值得考虑。这里的分类不是个人饮食处方。",
          ),
          example(
            "一份普通家常午餐",
            "米饭、清蒸鱼和炒青菜可以让你看到不同来源：米饭提供较多碳水，鱼提供蛋白质和一些脂肪，炒菜用油也提供脂肪。这只是辨认练习，不是每个人都必须照吃的菜单。",
          ),
        ],
        [
          p(
            "Carbohydrate, protein and fat are the three energy-providing macronutrients. “Macro” means we need relatively large amounts, usually measured in grams. It does not mean one is more important than another. Water is also needed in large amounts but supplies no energy; here we focus on the three that do.",
          ),
          comparison(
            {
              title: "Carbohydrate",
              items: [
                "Provides energy the body can use.",
                "Found in rice, noodles, fruit and beans, among other foods.",
                "Includes sugars, starch and fibre; fibre is not digested in the same way as starch.",
              ],
            },
            {
              title: "Protein",
              items: [
                "Supplies amino acids used to build and repair tissues.",
                "Also forms working substances such as enzymes.",
                "Eggs, fish, tofu and beans are familiar sources.",
              ],
            },
            {
              title: "Fat",
              items: [
                "Supplies energy and forms part of cell structures.",
                "Helps the body absorb vitamins A, D, E and K.",
                "Found in cooking oils, nuts, fish and eggs.",
              ],
            },
          ),
          p(
            "One food can supply several of these at once. Tofu provides protein and fat; rice is not pure carbohydrate. Calling a food “rich in” one nutrient highlights a feature, rather than describing everything it contains.",
          ),
          call(
            "important",
            "All three have legitimate roles",
            "Hearing “carbohydrate” or “fat” is not a reason to remove a whole food group. Food choices, amounts and the overall pattern over time matter. This classification is not a personalised eating prescription.",
          ),
          example(
            "An ordinary family lunch",
            "Rice, steamed fish and stir-fried vegetables illustrate different sources: rice supplies more carbohydrate, fish supplies protein and some fat, and cooking oil contributes fat. This is an identification exercise, not a menu everyone must follow.",
          ),
        ],
      ),
    },
    {
      id: "micronutrients",
      title: l(
        "1.3 微量营养素：少量，但不可轻视",
        "1.3 Micronutrients: small amounts, important jobs",
      ),
      termIds: ["micronutrient", "vitamin", "mineral"],
      sourceIds: ["who", "nutrition-terms"],
      content: l(
        [
          p(
            "维生素和矿物质统称为微量营养素，通常以毫克或微克计。它们不像供能的宏量营养素那样直接提供卡路里，却帮助身体的许多过程正常运作。“需要得少”和“无关紧要”完全不是一回事。",
          ),
          p(
            "维生素是一组不同的有机物质；矿物质是钙、铁等元素。你不需要现在背下所有名称。先认识两类，再逐渐学习各自的作用和食物来源。",
          ),
          list(
            "例如，维生素 C 参与胶原蛋白的形成。",
            "钙是骨骼和牙齿的重要组成部分，也参与其他身体功能。",
            "铁参与血红蛋白的组成，帮助血液运输氧气。",
          ),
          example(
            "不是只有蔬菜才有微量营养素",
            "水果、蔬菜、豆类、奶类、蛋类等食物都可以提供不同的维生素和矿物质。不同食物的组合，比只依赖一种所谓“超级食物”更能体现多样性。",
          ),
          call(
            "warning",
            "需要少量，不代表越多越好",
            "微量营养素过多也可能有害。补充剂不是本课的任务；是否需要补充要考虑年龄、饮食、怀孕、疾病和用药等情况，由合格专业人士指导。",
          ),
        ],
        [
          p(
            "Vitamins and minerals are called micronutrients. Their amounts are often measured in milligrams or micrograms. Unlike the energy-providing macronutrients, they do not directly supply calories, but they help many processes work properly. “Needed in small amounts” is very different from “unimportant.”",
          ),
          p(
            "Vitamins are a range of organic substances; minerals are elements such as calcium and iron. You do not need to memorise every name today. Start by recognising the two groups, then gradually learn their roles and food sources.",
          ),
          list(
            "For example, vitamin C helps with the formation of collagen.",
            "Calcium is an important part of bones and teeth and has other body functions too.",
            "Iron forms part of haemoglobin, helping the blood carry oxygen.",
          ),
          example(
            "Micronutrients are not just in vegetables",
            "Fruit, vegetables, beans, dairy foods and eggs can all provide different vitamins and minerals. A combination of foods expresses variety better than depending on one supposed “superfood.”",
          ),
          call(
            "warning",
            "Small requirements do not mean more is better",
            "Too much of some micronutrients can also cause harm. Starting supplements is not part of this lesson. Decisions depend on age, diet, pregnancy, health conditions and medicines, and may need qualified professional advice.",
          ),
        ],
      ),
    },
    {
      id: "energy",
      title: l("1.4 能量与卡路里", "1.4 Energy and calories"),
      termIds: ["calorie", "energy"],
      sourceIds: ["energy", "nutrition-terms"],
      content: l(
        [
          p(
            "身体即使在休息时也在工作：心脏跳动、呼吸、维持体温、更新细胞，都需要能量。走路、做家务和其他活动也需要能量。食物中的碳水化合物、蛋白质和脂肪能提供能量。",
          ),
          p(
            "卡路里是衡量能量的单位。日常营养语境里说的一个“卡路里”（英文食品标签上的 Calorie）通常指一千卡，写成 kcal；1 kcal 等于 1,000 个小卡（cal）。包装也可能用千焦 kJ 表示。看到这些单位时，先知道它们都在描述能量。",
          ),
          call(
            "remember",
            "能量不是另一种营养素",
            "营养素是物质；能量是身体从一些营养素中获得的做功能力。维生素、矿物质和水很重要，但本身并不直接提供卡路里。",
          ),
          example(
            "相同能量，不等于相同食物质量",
            "假设两份食物的标签都写着 100 kcal。这只能说明标示的能量相同，不能证明蛋白质、纤维、维生素或矿物质也一样。就像两只同样重的购物袋，里面装的东西可以完全不同。",
          ),
          p(
            "这一周不用计算减重目标，也不需要把每一口食物变成数字。先练习读懂一个概念：卡路里回答的是“有多少能量”，不能独自回答“这顿饭是否多样、适合我”。",
          ),
        ],
        [
          p(
            "Even at rest, the body is working: your heart beats, you breathe, maintain body temperature and renew cells. These processes need energy. Walking, housework and other activities need energy too. Carbohydrate, protein and fat in food can supply it.",
          ),
          p(
            "A calorie is a unit for measuring energy. In everyday nutrition, a “calorie” (a capital-C Calorie on food labels) usually means a kilocalorie, written kcal. One kcal equals 1,000 small calories (cal). Labels may also show kilojoules, or kJ. Both units describe energy.",
          ),
          call(
            "remember",
            "Energy is not another nutrient",
            "Nutrients are substances; energy is the capacity for work that the body obtains from some of them. Vitamins, minerals and water are important, but do not directly provide calories.",
          ),
          example(
            "Same energy, different food qualities",
            "Imagine two servings both labelled 100 kcal. Their stated energy is the same, but their protein, fibre, vitamins and minerals may differ. Two shopping bags can weigh the same while containing very different things.",
          ),
          p(
            "This week does not ask you to calculate a weight-loss target or turn every bite into a number. Learn one distinction first: calories answer “how much energy?” They cannot, on their own, tell you whether a meal is varied or appropriate for you.",
          ),
        ],
      ),
    },
    {
      id: "reference-values",
      title: l(
        "1.5 RDA、EAR 与 UL：三种不同的问题",
        "1.5 RDA, EAR and UL: three different questions",
      ),
      termIds: ["rda", "ear", "ul"],
      sourceIds: ["dri"],
      content: l(
        [
          p(
            "这些缩写来自膳食参考摄入量体系，用于健康人群的摄入规划与评估，不是诊断工具，也不是人人通用的处方。RDA 常用于个人膳食规划；EAR 更多用于群体评估。UL 表示长期摄入的风险边界，而不是努力达到的量。",
          ),
          comparison(
            {
              title: "RDA · 推荐膳食供给量",
              items: [
                "满足同一年龄与性别组中，几乎所有健康人的需要。",
                "可作为个人日常摄入规划的参考。",
              ],
            },
            {
              title: "EAR · 平均需要量",
              items: [
                "估计满足同一组中约一半健康人的需要。",
                "常用于评估群体摄入是否足够，不能当作人人的目标。",
              ],
            },
            {
              title: "UL · 可耐受最高摄入量",
              items: [
                "长期每日摄入在这一水平下，一般不太可能产生不良影响。",
                "这是上限参考，绝不是推荐目标。",
              ],
            },
          ),
          example(
            "看资料时，先问这个数字回答什么",
            "看到 EAR，想到“这组人需要量的中间位置”；看到 RDA，想到“照顾到大多数健康人的日常规划参考”；看到 UL，想到“摄入过多的风险”。它们不是从基础到高级的三个营养目标。",
          ),
          call(
            "warning",
            "UL 不是推荐目标",
            "不要为了“营养更足”而努力吃到 UL。超过上限，风险可能增加；低于上限也不等于对每个人都安全。某些营养素的上限只适用于补充剂或强化食品，需要看清适用说明。",
          ),
          p(
            "适用值会因年龄、性别和生命阶段而改变，不同国家的参考体系也可能不同。有些营养素缺少足够证据来设定 RDA 或 UL；“没有上限数据”不代表可以无限量摄入。个人健康、怀孕或用药相关问题，应请教合格专业人士。",
          ),
        ],
        [
          p(
            "These abbreviations belong to a dietary reference system for planning and assessing intake in healthy people. They are not diagnostic tests or universal prescriptions. RDA is often used for individual planning; EAR is more commonly used for group assessment. UL addresses excessive intake, not nutritional ambition.",
          ),
          comparison(
            {
              title: "RDA · Recommended Dietary Allowance",
              items: [
                "Designed to cover almost all healthy people in a particular age and sex group.",
                "A reference for planning an individual’s usual intake.",
              ],
            },
            {
              title: "EAR · Estimated Average Requirement",
              items: [
                "Estimated to cover about half of the healthy people in that group.",
                "Often used to assess groups; not a target for everyone.",
              ],
            },
            {
              title: "UL · Tolerable Upper Intake Level",
              items: [
                "A long-term daily intake level generally unlikely to cause harm.",
                "An upper-limit reference, never a recommended target.",
              ],
            },
          ),
          example(
            "Ask what the number is for",
            "Read EAR as a midpoint of requirements, RDA as a planning reference that covers most healthy people, and UL as a limit concerned with excess. These are not three levels of achievement.",
          ),
          call(
            "warning",
            "UL is not a recommended target",
            "Do not aim for UL to “maximise nutrition.” Risk may rise above it; being below it does not guarantee safety for every individual. Some limits apply only to supplements or fortified foods, so their scope matters.",
          ),
          p(
            "Values vary with age, sex and life stage, and countries may use different reference systems. Evidence is insufficient to set an RDA or UL for some nutrients. An absent UL is not permission for unlimited intake. Seek qualified advice for personal concerns involving health conditions, pregnancy or medicines.",
          ),
        ],
      ),
    },
    {
      id: "foods-and-nutrients",
      title: l(
        "1.6 回到餐桌：食物不只有一种成分",
        "1.6 Back to the table: foods contain combinations",
      ),
      termIds: ["fibre", "phytochemical"],
      sourceIds: ["who", "nutrition-terms"],
      content: l(
        [
          p(
            "现在回到最初的问题：我们吃的是食物，身体从中获得营养素。日常用“蛋白质”“碳水”来称呼整种食物很方便，但也容易让我们忽略食物中的其他成分。",
          ),
          comparison(
            {
              title: "一颗鸡蛋",
              items: [
                "提供蛋白质和脂肪。",
                "也有一些维生素与矿物质。",
                "不是只有蛋白质。",
              ],
            },
            {
              title: "一碗米饭",
              items: [
                "主要提供碳水化合物，也有一些蛋白质。",
                "米的种类、加工和烹调会影响其他成分。",
                "糙米与白米的纤维等成分不完全一样。",
              ],
            },
            {
              title: "一盘蔬菜",
              items: [
                "可以提供纤维、维生素和矿物质。",
                "也含植物化学物，例如不同的色素。",
                "“植物化学物”不等于有治病效果。",
              ],
            },
          ),
          p(
            "纤维属于碳水化合物，但不是所有纤维都会像淀粉一样被消化；有些可以被肠道微生物利用。植物化学物是植物中的多种天然化合物，并不都属于必需营养素。遇到新的词，先查本页术语，不必马上离开课程。",
          ),
          example(
            "在杂饭档做一次观察",
            "看看米饭、豆腐、鱼和青菜。试着为每种食物说出两类可能含有的营养成分。你不需要猜出精确克数；目标是看见组合，而不是给整道菜打“好”或“坏”的分数。",
          ),
          p(
            "食物还与文化、口味、预算和方便程度有关。营养知识是帮助我们理解选择的工具，不应该让一顿家庭饭变成考试。下一步，把这个观察方法用到你今天吃的一顿饭上。",
          ),
        ],
        [
          p(
            "Return to our starting point: we eat foods and obtain nutrients from them. Calling a whole food “protein” or “carbs” is convenient shorthand, but it can hide the other things that food contains.",
          ),
          comparison(
            {
              title: "An egg",
              items: [
                "Provides protein and fat.",
                "Also supplies some vitamins and minerals.",
                "It is not just protein.",
              ],
            },
            {
              title: "A bowl of rice",
              items: [
                "Provides mainly carbohydrate and some protein.",
                "Variety, processing and cooking affect other components.",
                "Brown and white rice differ in fibre and other components.",
              ],
            },
            {
              title: "A plate of vegetables",
              items: [
                "Can supply fibre, vitamins and minerals.",
                "Also contains phytochemicals, such as plant pigments.",
                "“Phytochemical” does not mean a substance cures disease.",
              ],
            },
          ),
          p(
            "Fibre is a carbohydrate, but is not all digested like starch; some can be used by gut microbes. Phytochemicals are many different natural plant compounds, and not all are essential nutrients. When a word is unfamiliar, use this page’s key terms rather than leaving the lesson.",
          ),
          example(
            "Observe a mixed-rice stall",
            "Look at the rice, tofu, fish and vegetables. Try naming two nutrient groups each food may contain. You do not need to guess exact grams. The aim is to recognise combinations, not give each dish a “good” or “bad” score.",
          ),
          p(
            "Food also involves culture, taste, budget and convenience. Nutrition knowledge should help you understand choices, not turn a family meal into an exam. Next, apply this way of observing to one meal you ate today.",
          ),
        ],
      ),
    },
  ],
  keyTerms: [
    term(
      "nutrition",
      "营养学",
      "Nutrition",
      "研究食物中的成分及身体如何利用它们的学科。",
      "The study of substances in food and how the body uses them.",
    ),
    term(
      "nutrient",
      "营养素",
      "Nutrient",
      "身体需要利用的食物成分，例如蛋白质、维生素或矿物质。不是所有食物成分都属于必需营养素。",
      "A substance in food that the body needs and uses, such as protein, a vitamin or a mineral. Not every food component is an essential nutrient.",
      "鸡蛋是食物，蛋白质是其中的一类营养素。",
      "An egg is a food; protein is one nutrient it contains.",
    ),
    term(
      "macronutrient",
      "宏量营养素",
      "Macronutrient",
      "需要量较大的营养素。本课的三类供能宏量营养素是碳水化合物、蛋白质和脂肪。",
      "A nutrient needed in relatively large amounts. The three energy-providing ones discussed here are carbohydrate, protein and fat.",
    ),
    term(
      "carbohydrate",
      "碳水化合物",
      "Carbohydrate",
      "包括糖、淀粉和纤维的一类物质。糖和淀粉可被消化并为身体提供能量；纤维的利用方式不同。",
      "A group including sugars, starch and fibre. Sugars and starch can be digested to provide energy; fibre is used differently.",
    ),
    term(
      "protein",
      "蛋白质",
      "Protein",
      "由氨基酸构成。消化后提供身体用于制造组织和多种功能性物质的原料。",
      "Made from amino acids. Digestion supplies materials the body uses to build tissues and many working substances.",
    ),
    term(
      "amino-acid",
      "氨基酸",
      "Amino acid",
      "构成蛋白质的基本小分子。蛋白质经过消化被分解后，身体可以重新利用氨基酸来构建和修复组织。",
      "A small molecule that forms a building block of protein. After protein is broken down during digestion, the body can reuse amino acids to build and repair tissues.",
    ),
    term(
      "fat",
      "脂肪",
      "Fat",
      "一类供能营养素，也是细胞结构的重要组成部分，并帮助吸收某些维生素。",
      "An energy-providing nutrient that also contributes to cell structures and helps with absorption of certain vitamins.",
    ),
    term(
      "micronutrient",
      "微量营养素",
      "Micronutrient",
      "需要量相对较小的维生素和矿物质，通常以毫克或微克计；少量并不代表不重要。",
      "Vitamins and minerals required in relatively small amounts, often measured in milligrams or micrograms. Small does not mean unimportant.",
    ),
    term(
      "vitamin",
      "维生素",
      "Vitamin",
      "身体少量需要的一组有机物质，支持不同的正常功能；它们本身不直接提供卡路里。",
      "One of a group of organic substances needed in small amounts for normal functions. Vitamins do not directly supply calories.",
    ),
    term(
      "mineral",
      "矿物质",
      "Mineral",
      "钙、铁等身体需要的元素，参与结构或功能。矿物质本身不直接提供卡路里。",
      "An element, such as calcium or iron, needed for body structures or functions. Minerals do not directly supply calories.",
    ),
    term(
      "energy",
      "能量",
      "Energy",
      "身体进行活动和维持生命过程所需的做功能力；可以从某些营养素中获得。",
      "The capacity to do work, needed for movement and life processes. The body obtains it from certain nutrients.",
    ),
    term(
      "calorie",
      "卡路里／千卡",
      "Calorie / kilocalorie",
      "能量单位。在营养语境中一个 Calorie 通常指 1 kcal，即 1,000 cal；它不是食物质量评分。",
      "A unit of energy. In nutrition, a Calorie usually means 1 kcal, equal to 1,000 cal; it is not a food-quality score.",
    ),
    term(
      "rda",
      "推荐膳食供给量",
      "RDA",
      "为满足同一年龄与性别组几乎所有健康人的营养需要而设定的日常摄入参考。",
      "A usual-intake reference intended to meet the needs of almost all healthy people in a particular age and sex group.",
    ),
    term(
      "ear",
      "平均需要量",
      "EAR",
      "估计满足某一组约一半健康人需要的日常摄入水平，常用于群体评估。",
      "The intake estimated to meet the needs of about half of a specified healthy group, often used for group assessment.",
    ),
    term(
      "ul",
      "可耐受最高摄入量",
      "UL",
      "长期摄入一般不太可能导致不良影响的上限参考，不是每日应追求的目标。",
      "An upper reference for long-term intake generally unlikely to cause harm, not a daily target to aim for.",
    ),
    term(
      "fibre",
      "膳食纤维",
      "Dietary fibre",
      "不能像淀粉那样被人体消化的一类碳水化合物；其中一些可被肠道微生物利用。",
      "Carbohydrates not digested by the body in the same way as starch; some can be used by gut microbes.",
    ),
    term(
      "phytochemical",
      "植物化学物",
      "Phytochemical",
      "植物中的天然化合物，例如一些色素；并不都属于必需营养素，也不能由名称推断治病效果。",
      "A natural plant compound, such as certain pigments. Not all are essential nutrients, and the name does not imply disease-treatment effects.",
    ),
  ],
  questions: [
    question(
      "food-nutrient",
      l(
        "鸡蛋和蛋白质有什么区别？",
        "What is the difference between an egg and protein?",
      ),
      [
        l(
          "鸡蛋是食物，蛋白质是它含有的一类营养素。",
          "An egg is a food; protein is one nutrient it contains.",
        ),
        l(
          "鸡蛋和蛋白质是完全相同的东西。",
          "An egg and protein are exactly the same thing.",
        ),
        l("鸡蛋只含蛋白质。", "An egg contains only protein."),
      ],
      0,
      l(
        "正确区分食物和营养素是第一步。鸡蛋还含脂肪、维生素和矿物质，并不只有蛋白质。",
        "Separate the food from its components. An egg also contains fat, vitamins and minerals; it is not only protein.",
      ),
    ),
    question(
      "micro",
      l("以下哪一项属于微量营养素？", "Which is a micronutrient?"),
      [
        l("脂肪", "Fat"),
        l("维生素 C", "Vitamin C"),
        l("碳水化合物", "Carbohydrate"),
      ],
      1,
      l(
        "维生素 C 是维生素，属于微量营养素。需要的量较小，但作用仍然重要。脂肪和碳水化合物属于宏量营养素。",
        "Vitamin C is a vitamin, so it is a micronutrient. Its required amount is small but its role matters. Fat and carbohydrate are macronutrients.",
      ),
    ),
    question(
      "energy-quality",
      l(
        "两份食物都是 100 kcal，能说明什么？",
        "Two servings both provide 100 kcal. What does that tell us?",
      ),
      [
        l("两者营养成分完全相同。", "Their nutrients are identical."),
        l("两者适合每一个人。", "Both suit every person."),
        l(
          "标示能量相同，但营养组成可能不同。",
          "Their stated energy is equal, but their nutrient composition may differ.",
        ),
      ],
      2,
      l(
        "卡路里描述能量。判断食物还需要看成分、份量和整体饮食情境。",
        "Calories describe energy. Food composition, amounts and the overall eating context matter too.",
      ),
    ),
    question(
      "ul-target",
      l(
        "UL 是每天应该努力吃到的量吗？",
        "Is UL the amount you should try to reach every day?",
      ),
      [
        l("是，越靠近上限越好。", "Yes, closer to the limit is better."),
        l(
          "不是，UL 是上限参考，不是推荐目标。",
          "No. UL is an upper-limit reference, not a recommended target.",
        ),
      ],
      1,
      l(
        "UL 关注摄入过多的风险，不是营养目标。需要看适用人群与来源说明，不能据此自行决定补充剂剂量。",
        "UL concerns the risk of excessive intake, not a nutritional goal. Its population and source limits matter; it is not a basis for choosing your own supplement dose.",
      ),
    ),
  ],
  practicalTask: l(
    "记录今天的一顿饭，列出食材，并尝试指出每种食物提供的营养素。不要只给食物贴“好”或“坏”的标签。",
    "Record one meal you ate today. List its ingredients and identify some nutrients each food may provide. Avoid simply labelling foods as “good” or “bad.”",
  ),
  summary: l(
    [
      "食物通常含有多种营养素，而不是只有一种。",
      "碳水化合物、蛋白质和脂肪都有合理的角色。",
      "维生素和矿物质需要量较小，但同样重要。",
      "卡路里描述能量，不代表食物的整体质量。",
      "RDA、EAR 和 UL 各有用途；UL 不是推荐目标。",
    ],
    [
      "Foods usually contain combinations of nutrients, not just one.",
      "Carbohydrate, protein and fat all have legitimate roles.",
      "Vitamins and minerals are needed in smaller amounts but still matter.",
      "Calories describe energy, not overall food quality.",
      "RDA, EAR and UL serve different purposes; UL is not a recommended target.",
    ],
  ),
};
